### ISSUE TITLE
Fails to compile with qt-5.11.0

### ISSUE THREAD

**Issue by nbvcxz** [palinek/nm-tray#22]
Got this error trying to compile from aur.archlinux.org with newest **qt-5.11.0-1** from **extra** (stable) repo
```
[ 62%] Building CXX object CMakeFiles/nm-tray.dir/src/nmproxy.cpp.o
[ 65%] Building CXX object CMakeFiles/nm-tray.dir/src/connectioninfo.cpp.o
/tmp/yaourt-tmp-nbvcxz/aur-nm-tray-git/src/nm-tray/src/connectioninfo.cpp: In member function ‘void ConnectionInfo::changeTab(const QModelIndex&)’:
/tmp/yaourt-tmp-nbvcxz/aur-nm-tray-git/src/nm-tray/src/connectioninfo.cpp:100:28: error: invalid use of incomplete type ‘class QTabBar’
     ui->tabWidget->tabBar()->setTabText(i, mSorted->data(index, NmModel::NameRole).toString());
                            ^~
In file included from /usr/include/qt/QtWidgets/QTabWidget:1,
                 from /tmp/yaourt-tmp-nbvcxz/aur-nm-tray-git/src/build/nm-tray_autogen/include/ui_connectioninfo.h:16,
                 from /tmp/yaourt-tmp-nbvcxz/aur-nm-tray-git/src/nm-tray/src/connectioninfo.cpp:24:
/usr/include/qt/QtWidgets/qtabwidget.h:51:7: note: forward declaration of ‘class QTabBar’
 class QTabBar;
       ^~~~~~~
/tmp/yaourt-tmp-nbvcxz/aur-nm-tray-git/src/nm-tray/src/connectioninfo.cpp:101:28: error: invalid use of incomplete type ‘class QTabBar’
     ui->tabWidget->tabBar()->setTabIcon(i,  mSorted->data(index, NmModel::IconRole).value<QIcon>());
                            ^~
In file included from /usr/include/qt/QtWidgets/QTabWidget:1,
                 from /tmp/yaourt-tmp-nbvcxz/aur-nm-tray-git/src/build/nm-tray_autogen/include/ui_connectioninfo.h:16,
                 from /tmp/yaourt-tmp-nbvcxz/aur-nm-tray-git/src/nm-tray/src/connectioninfo.cpp:24:
/usr/include/qt/QtWidgets/qtabwidget.h:51:7: note: forward declaration of ‘class QTabBar’
 class QTabBar;
       ^~~~~~~
make[2]: *** [CMakeFiles/nm-tray.dir/build.make:170: CMakeFiles/nm-tray.dir/src/connectioninfo.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/nm-tray.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by palinek** [comment]
@nbvcxz thanks. Please, try with 8137189
